export HADOOP_USER_NAME=spark
export HOME=/tmp
export SPARK_LOCAL_DIRS=/tmp
export HADOOP_CONF_DIR=""
export HADOOP_SECURITY_AUTHENTICATION=simple
export HADOOP_SECURITY_AUTHORIZATION=false
export SPARK_SECURITY_CREDENTIALS_PROVIDER=""
export JAVA_SECURITY_KRB5_CONF=""
